

title: Echo Future Truth

description: A Creation Story in Three Parts 

author: By D.P. Maddalena

baseurl: "" 
url: "https://echofuturetruth.com" 

icon: /assets/images/favicon.ico

email: hello@echofuturetruth.com

markdown: kramdown

hide_credits: true
hide_search: true

