

title: Echo Future Truth

description: A Creation Story in Three Parts 

author: By D.P. Maddalena

baseurl: "" 
url: "https://echofuturetruth.com" 

icon: /assets/images/favicon.ico

email: hello@echofuturetruth.com

markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  input: GFM
  entity_output: as_char
  typographic_symbols:
    hellip: "..."

hide_credits: true
hide_search: true

